CustomForm/Controllers/BBController.cs
using CustomForm.Entities;
using CustomForm.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace CustomForm.Controllers
{
    public class BBController : BaseController
    {
        private readonly IFreeSql _sql;

        public BBController(IFreeSql sql)
        {
            _sql = sql;
        }

        [HttpGet]
        public IActionResult All(int page = 1, int size = 10)
        {
            var list = _sql.Select<BB>().From<BB_flpx, User>((s, b, c) => s
             .LeftJoin(a => a.fbfl == b.id)
             .LeftJoin(a => a.userid == c.id))
            .OrderByDescending((a, b, c) => a.id)
            .Count(out var count)
            .Page(page, size)
            .ToList((a, b, c) => new BBItemViewModel
            {
                id = a.id,
                userid = a.userid,
                fbsj = a.fbsj,
                fbfl = a.fbfl,
                fbbt = a.fbbt,
                flmc = b.flmc,
                username = c.username
            });

            var model = new BBViewModel() { BBList = list, BBCount = count };
            return View(model);
        }

        [HttpGet]
        public IActionResult My(int page = 1, int size = 10)
        {
            var list = _sql.Select<BB>().From<BB_flpx, User>((s, b, c) => s
             .LeftJoin(a => a.fbfl == b.id)
             .LeftJoin(a => a.userid == c.id))
             .Where((a, b, c) => a.userid == Admin.adminid)
            .OrderByDescending((a, b, c) => a.id)
            .Count(out var count)
            .Page(page, size)
            .ToList((a, b, c) => new BBItemViewModel
            {
                id = a.id,
                userid = a.userid,
                fbsj = a.fbsj,
                fbfl = a.fbfl,
                fbbt = a.fbbt,
                flmc = b.flmc,
                username = c.username
            });

            var model = new BBViewModel() { BBList = list, BBCount = count };
            return View(model);
        }

        [HttpGet]
        public IActionResult Show(long id)
        {
            var model = _sql.Select<BB>().From<BB_flpx, User>((s, b, c) => s
             .LeftJoin(a => a.fbfl == b.id)
             .LeftJoin(a => a.userid == c.id))
            .Where((a, b, c) => a.id == id)
            .ToOne((a, b, c) => new BBItemViewModel
            {
                id = a.id,
                userid = a.userid,
                fbsj = a.fbsj,
                fbfl = a.fbfl,
                fbbt = a.fbbt,
                flmc = b.flmc,
                username = c.username
            });

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Form(long id = 0)
        {
            var categories = await _sql.Select<BB_flpx>().OrderByDescending(c => c.flpx).ToListAsync();
            ViewBag.Categories = categories;

            var form = new BBFormViewModel() { id = id, fbfl = 1 };
            if (id > 0)
            {
                var bb = await _sql.Select<BB>(new { id }).ToOneAsync();
                form = bb == null ? form : new BBFormViewModel() { id = bb.id, fbbt = bb.fbbt, fbfl = bb.fbfl, fblr = bb.fblr };
            }
            return View(form);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Form(BBFormViewModel form)
        {
            if (ModelState.IsValid)
            {
                var bb = new BB
                {
                    fbsj = DateTime.Now,
                    userid = Admin.adminid
                };

                if (form.id > 0)
                {
                    bb = await _sql.Select<BB>(new { form.id }).ToOneAsync();
                }

                bb.fbfl = form.fbfl;
                bb.fbbt = form.fbbt;
                bb.fblr = form.fblr;

                await _sql.InsertOrUpdate<BB>().SetSource(bb).ExecuteAffrowsAsync();
                return RedirectToAction(nameof(My));
            }

            var categories = await _sql.Select<BB_flpx>().OrderByDescending(c => c.flpx).ToListAsync();
            ViewBag.Categories = categories;

            return View(form);
        }

        [HttpGet]
        public async Task<IActionResult> Del(long id)
        {
            await _sql.Delete<BB>(new { id }).ExecuteAffrowsAsync();
            return RedirectToAction(nameof(My));
        }


        [HttpGet]
        public async Task<IActionResult> CateList(int page = 1, int size = 10)
        {
            var list = await _sql.Select<BB_flpx>().OrderByDescending(c => c.flpx).Count(out var count).Page(page, size).ToListAsync();
            var model = new BBCateViewModel() { CateList = list, ListCount = count };
            return View(model);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CateForm(long id, BBCateFormViewModel model)
        {
            var source = new BB_flpx() { id = id, flpx = model.flpx, flmc = model.flmc };
            await _sql.InsertOrUpdate<BB_flpx>().SetSource(source).ExecuteAffrowsAsync();
            return RedirectToAction(nameof(CateList));
        }

        [HttpGet]
        public async Task<IActionResult> CateDel(long id)
        {
            await _sql.Delete<BB_flpx>(new { id }).ExecuteAffrowsAsync();
            return RedirectToAction(nameof(CateList));
        }

    }
}

CustomForm/Controllers/UserController.cs
using CustomForm.Common.Extensions;
using CustomForm.Entities;
using CustomForm.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace CustomForm.Controllers
{
    public class UserController : BaseController
    {
        private readonly IFreeSql _sql;

        public UserController(IFreeSql sql)
        {
            _sql = sql;
        }

        [HttpGet]
        public async Task<IActionResult> List(int page = 1, int size = 10)
        {
            var list = await _sql.Select<User>().From<User>((s, b) => s.LeftJoin(a => a.pid == b.id))
            .Count(out var count).Page(page, size)
            .ToListAsync((a, b) => new UserItemViewModel
            {
                id = a.id,
                username = a.username,
                pid = a.pid,
                pname = b.username,
                quanxian = a.quanxian,
                danwei = a.danwei,
                xingming = a.xingming,
                dianhua = a.dianhua,
                email = a.email,
                zhucesj = a.zhucesj
            });

            var model = new UserViewModel() { UserList = list, ListCount = count };
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Form(long id)
        {
            var model = new UserFormViewModel() { id = 0, oaid = Admin.oaid, danwei = Admin.danwei };

            if (id > 0)
            {
                model = await _sql.Select<User>().Where(a => a.id == id)
                  .ToOneAsync(a => new UserFormViewModel
                  {
                      id = a.id,
                      oaid = a.oaid,
                      pid = a.pid,
                      danwei = a.danwei,
                      xingming = a.xingming,
                      touxiang = a.touxiang,
                      dianhua = a.dianhua,
                      email = a.email,
                      remark = a.remark
                  });
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Form(UserFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                var source = new User()
                {
                    id = model.id,
                    touxiang = 0,
                    quanxian = "管理",
                    username = model.username,
                    password = model.password.MD5(true),
                    zhucesj = DateTime.Now
                };

                if (model.id > 0)
                {
                    source = await _sql.Select<User>(new { id = model.id }).ToOneAsync();
                }

                source.oaid = model.oaid;
                source.pid = model.pid;
                source.danwei = model.danwei;
                source.xingming = model.xingming;
                source.dianhua = model.dianhua;
                source.email = model.email;
                source.remark = model.remark;

                await _sql.InsertOrUpdate<User>().SetSource(source).ExecuteAffrowsAsync();
                return RedirectToAction(nameof(List));
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Del(int id)
        {
            await _sql.Delete<User>(new { id }).ExecuteAffrowsAsync();
            return RedirectToAction(nameof(List));
        }
    }
}

CustomForm/Views/Shared/_Layout.cshtml
@{
    var session = ViewContext.HttpContext.Session.Get<AdminSession>(nameof(AdminSession));
}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no" />
    <title>CustomForm</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/fonts.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    @await RenderSectionAsync("Styles", required: false)
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="ftdms-layout-web">
        <div class="ftdms-layout-container">
            <!--左侧导航-->
            <aside class="ftdms-layout-sidebar">
                <!-- logo -->
                <div id="logo" class="sidebar-header"><a><img src="~/images/admin_logo.png" /></a></div>
                <div class="ftdms-layout-sidebar-scroll">
                    <nav class="sidebar-main">
                        <ul class="nav nav-drawer">
                            <li class="nav-item"> <a href="/"><i class="ftsucai-82"></i>后台首页</a> </li>
                            <li class="nav-item nav-item-has-subnav  @((int)ViewData["Menu"] == 1 ? " open": "")">
                                <a href="javascript:void(0)"><i class="ftsucai-UI"></i> 新闻通知</a>
                                <ul class="nav nav-subnav">
                                    <li> <a href="@Url.Action("All","BB")">全部信息</a> </li>
                                </ul>
                            </li>

                            <li class="nav-item nav-item-has-subnav @((int)ViewData["Menu"] == 7 ? " open": "")">
                                <a href="javascript:void(0)"><i class="ftsucai-table"></i> 填表任务</a>
                                <ul class="nav nav-subnav">
                                    @if (session.adminqx == "超管")
                                    {
                                        <li> <a href="../7/form_all.asp">全部填表</a> </li>
                                        <li> <a href="../7/form_all_my.asp">我的填表</a> </li>
                                    }
                                    <li> <a href="../7/form_list_dw.asp">报表查询</a> </li>
                                    @if (session.adminqx == "超管")
                                    {
                                        <li> <a href="../7/form_add.asp">新建填表</a> </li>
                                    }
                                </ul>
                            </li>

                            @if (session.adminqx == "超管")
                            {
                                <li class="nav-item nav-item-has-subnav @((int)ViewData["Menu"] == 8 ? " open": "")">
                                    <a href="javascript:void(0)"><i class="ftsucai-25"></i> 信息管理</a>
                                    <ul class="nav nav-subnav">
                                        <li> <a href="@Url.Action("My","BB")">我的发布</a> </li>
                                        <li> <a href="@Url.Action("Form","BB")">发布信息</a> </li>
                                        <li> <a href="@Url.Action("CateList","BB")">分类管理</a> </li>
                                    </ul>
                                </li>
                            }

                            <li class="nav-item nav-item-has-subnav  @((int)ViewData["Menu"] == 9 ? " open": "")">
                                <a href="javascript:void(0)"><i class="ftsucai-setup-4"></i> 系统设置</a>
                                <ul class="nav nav-subnav">
                                    <li> <a href="@Url.Action("SetUser","Home")">个人信息</a> </li>
                                    <li> <a href="@Url.Action("SetPass","Home")">修改密码</a> </li>
                                    <li> <a href="@Url.Action("Form", "User")">新增人员</a> </li>
                                    <li> <a href="@Url.Action("List", "User")">人员列表</a> </li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </aside>
            <!--End 左侧导航-->
            <!--头部信息-->
            <header class="ftdms-layout-header">
                <nav class="navbar navbar-default">
                    <div class="topbar">

                        <div class="topbar-left">
                            <div class="ftdms-aside-toggler">
                                <span class="ftdms-toggler-bar"></span>
                                <span class="ftdms-toggler-bar"></span>
                                <span class="ftdms-toggler-bar"></span>
                            </div>
                            <span class="navbar-page-title"> @ViewData["Title"] </span>
                        </div>

                        <ul class="topbar-right">
                            <li class="dropdown dropdown-profile">
                                <a href="javascript:void(0)" data-toggle="dropdown">
                                    <span>@(session.adminuser)（@session.adminqx）<span class="caret"></span></span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li> <a href="@Url.Action("SetUser","Home")"><i class="ftsucai-58"></i> 个人信息</a> </li>
                                    <li> <a href="@Url.Action("SetPass","Home")"><i class="ftsucai-edit-2"></i> 修改密码</a> </li>
                                    <li class="divider"></li>
                                    <li> <a href="@Url.Action("Logout", "Home")"><i class="ftsucai-exit2"></i> 退出登录</a> </li>
                                </ul>
                            </li>
                        </ul>

                    </div>
                </nav>

            </header>
            <!--End 头部信息-->
            <!--页面主要内容-->
            @RenderBody()
            <!--End 页面主要内容-->
        </div>
    </div>
    <script type="text/javascript">
        function preview(eee){
            var style = document.createElement('style');
            if(eee=='1'){
                style.innerHTML = "@@page {size: portrait}";
            }else{
                style.innerHTML = "@@page {size: landscape}";
            }
            window.document.head.appendChild(style);
            bdhtml=window.document.body.innerHTML;//获取当前页的html代码
            sprnstr="<!--startprint-->";
            eprnstr="<!--endprint-->";//设置打印区域
            prnhtml=bdhtml.substr(bdhtml.indexOf(sprnstr)+17);//从开始代码向后取html
            prnhtml=prnhtml.substring(0,prnhtml.indexOf(eprnstr));//从结束代码向前取html
            window.document.body.innerHTML=prnhtml;
            window.print();
            window.document.body.innerHTML=bdhtml;
        }
    </script>
    <script type="text/javascript" src="~/js/jquery.min.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/perfect-scrollbar.min.js"></script>
    <script type="text/javascript" src="~/js/main.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>