CustomForm/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CustomForm.Models
{
    public class HomeViewModel
    {
        public List<HomeBBViewModel> BBList { get; set; }
        public long BBListCount { get; set; }
    }

    public class HomeBBViewModel
    {
        public long id { get; set; }
        public long userid { get; set; }

        public DateTime fbsj { get; set; }
        public int fbfl { get; set; }
        public string fblr { get; set; }
        public string fbbt { get; set; }

        public string flmc { get; set; }
        public string username { get; set; }
    }

    public class SetUserViewModel
    {
        public long id { get; set; }

        public int oaid { get; set; }
        public long pid { get; set; }

        public string danwei { get; set; }
        public string xingming { get; set; }
        public long touxiang { get; set; }

        public string quanxian { get; set; }

        public string dianhua { get; set; }
        public string email { get; set; }
        public string remark { get; set; }
    }

    public class SetPassViewModel
    {
        [Required]
        public string pass0 { get; set; }
        [Required]
        public string pass1 { get; set; }
        [Required]
        public string pass2 { get; set; }
    }
}

CustomForm/Controllers/BBController.cs
using CustomForm.Entities;
using CustomForm.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace CustomForm.Controllers
{
    public class BBController : BaseController
    {
        private readonly IFreeSql _sql;

        public BBController(IFreeSql sql)
        {
            _sql = sql;
        }

        [HttpGet]
        public IActionResult All(int page = 1, int size = 10)
        {
            var list = _sql.Select<BB>().From<BB_flpx, User>((s, b, c) => s
             .LeftJoin(a => a.fbfl == b.id)
             .LeftJoin(a => a.userid == c.id))
            .OrderByDescending((a, b, c) => a.id)
            .Count(out var count)
            .Page(page, size)
            .ToList((a, b, c) => new BBItemViewModel
            {
                id = a.id,
                userid = a.userid,
                fbsj = a.fbsj,
                fbfl = a.fbfl,
                fbbt = a.fbbt,
                flmc = b.flmc,
                username = c.username
            });

            var model = new BBViewModel() { BBList = list, BBCount = count };
            return View(model);
        }

        [HttpGet]
        public IActionResult My(int page = 1, int size = 10)
        {
            var list = _sql.Select<BB>().From<BB_flpx, User>((s, b, c) => s
             .LeftJoin(a => a.fbfl == b.id)
             .LeftJoin(a => a.userid == c.id))
             .Where((a, b, c) => a.userid == Admin.adminid)
            .OrderByDescending((a, b, c) => a.id)
            .Count(out var count)
            .Page(page, size)
            .ToList((a, b, c) => new BBItemViewModel
            {
                id = a.id,
                userid = a.userid,
                fbsj = a.fbsj,
                fbfl = a.fbfl,
                fbbt = a.fbbt,
                flmc = b.flmc,
                username = c.username
            });

            var model = new BBViewModel() { BBList = list, BBCount = count };
            return View(model);
        }

        [HttpGet]
        public IActionResult Show(long id)
        {
            var model = _sql.Select<BB>().From<BB_flpx, User>((s, b, c) => s
             .LeftJoin(a => a.fbfl == b.id)
             .LeftJoin(a => a.userid == c.id))
            .Where((a, b, c) => a.id == id)
            .ToOne((a, b, c) => new BBItemViewModel
            {
                id = a.id,
                userid = a.userid,
                fbsj = a.fbsj,
                fbfl = a.fbfl,
                fbbt = a.fbbt,
                flmc = b.flmc,
                username = c.username
            });

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Form(long id = 0)
        {
            var categories = await _sql.Select<BB_flpx>().OrderByDescending(c => c.flpx).ToListAsync();
            ViewBag.Categories = categories;

            var form = new BBFormViewModel() { id = id, fbfl = 1 };
            if (id > 0)
            {
                var bb = await _sql.Select<BB>(new { id }).ToOneAsync();
                form = bb == null ? form : new BBFormViewModel() { id = bb.id, fbbt = bb.fbbt, fbfl = bb.fbfl, fblr = bb.fblr };
            }
            return View(form);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Form(BBFormViewModel form)
        {
            if (ModelState.IsValid)
            {
                var bb = new BB
                {
                    fbsj = DateTime.Now,
                    userid = Admin.adminid
                };

                if (form.id > 0)
                {
                    bb = await _sql.Select<BB>(new { form.id }).ToOneAsync();
                }

                bb.fbfl = form.fbfl;
                bb.fbbt = form.fbbt;
                bb.fblr = form.fblr;

                await _sql.InsertOrUpdate<BB>().SetSource(bb).ExecuteAffrowsAsync();
                return RedirectToAction(nameof(My));
            }

            var categories = await _sql.Select<BB_flpx>().OrderByDescending(c => c.flpx).ToListAsync();
            ViewBag.Categories = categories;

            return View(form);
        }

        [HttpGet]
        public async Task<IActionResult> Del(long id)
        {
            await _sql.Delete<BB>(new { id }).ExecuteAffrowsAsync();
            return RedirectToAction(nameof(My));
        }


        [HttpGet]
        public async Task<IActionResult> CateList(int page = 1, int size = 10)
        {
            var list = await _sql.Select<BB_flpx>().OrderByDescending(c => c.flpx).Count(out var count).Page(page, size).ToListAsync();
            var model = new BBCateViewModel() { CateList = list, ListCount = count };
            return View(model);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CateForm(long id, BBCateFormViewModel model)
        {
            var source = new BB_flpx() { id = id, flpx = model.flpx, flmc = model.flmc };
            await _sql.InsertOrUpdate<BB_flpx>().SetSource(source).ExecuteAffrowsAsync();
            return RedirectToAction(nameof(CateList));
        }

        [HttpGet]
        public async Task<IActionResult> CateDel(long id)
        {
            await _sql.Delete<BB_flpx>(new { id }).ExecuteAffrowsAsync();
            return RedirectToAction(nameof(CateList));
        }

    }
}

CustomForm/Controllers/HomeController.cs
using CustomForm.Common.Extensions;
using CustomForm.Entities;
using CustomForm.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CustomForm.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IFreeSql _sql;

        public HomeController(ILogger<HomeController> logger, IFreeSql sql)
        {
            _logger = logger;
            _sql = sql;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int page = 1, int size = 5)
        {
            var list = await _sql.Select<BB>().From<BB_flpx, User>((s, b, c) => s
             .LeftJoin(a => a.fbfl == b.id)
             .LeftJoin(a => a.userid == c.id))
            .OrderByDescending((a, b, c) => a.id)
            .Count(out var count)
            .Page(page, size)
            .ToListAsync((a, b, c) => new HomeBBViewModel
            {
                id = a.id,
                userid = a.userid,
                fbsj = a.fbsj,
                fbfl = a.fbfl,
                fbbt = a.fbbt,
                flmc = b.flmc,
                username = c.username
            });

            var model = new HomeViewModel() { BBList = list, BBListCount = count };
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> SetUser()
        {
            var model = await _sql.Select<User>().Where(a => a.id == Admin.adminid)
               .ToOneAsync(a => new SetUserViewModel
               {
                   id = a.id,
                   oaid = a.oaid,
                   pid = a.pid,
                   danwei = a.danwei,
                   xingming = a.xingming,
                   touxiang = a.touxiang,
                   dianhua = a.dianhua,
                   email = a.email,
                   remark = a.remark
               });

            return View(model);
        }

        public async Task<IActionResult> SetUser(SetUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var source = await _sql.Select<User>(new { id = model.id }).ToOneAsync();

                source.oaid = model.oaid;
                source.pid = model.pid;
                if (source.pid == Admin.adminid)
                {
                    source.pid = 0;
                }
                source.danwei = model.danwei;
                source.xingming = model.xingming;
                source.dianhua = model.dianhua;
                source.email = model.email;
                source.remark = model.remark;

                await _sql.InsertOrUpdate<User>().SetSource(source).ExecuteAffrowsAsync();
                return Redirect("~/");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult SetPass()
        {
            return View(new SetPassViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> SetPass(SetPassViewModel model)
        {
            if (ModelState.IsValid)
            {
                var source = await _sql.Select<User>(new { id = Admin.adminid }).ToOneAsync();
                if (model.pass0.MD5(true).Equals(source.password))
                {
                    if (model.pass1.Equals(model.pass2))
                    {
                        source.password = model.pass1.MD5(true);
                        await _sql.Update<User>().SetSource(source).ExecuteAffrowsAsync();
                    }
                }
                return Redirect("~/");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove(nameof(AdminSession));
            HttpContext.Session.Clear();

            return Redirect("/Login");
        }
    }
}

CustomForm/Controllers/UploadController.cs
using CustomForm.Common;
using CustomForm.Common.Extensions;
using CustomForm.Entities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Threading.Tasks;

namespace CustomForm.Controllers
{
    public class UploadController : Controller
    {
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IFreeSql _sql;

        public UploadController(IWebHostEnvironment hostEnvironment, IFreeSql sql)
        {
            _hostEnvironment = hostEnvironment;
            _sql = sql;
        }

        [HttpGet]
        public IActionResult Avatar(long id, long objectId, UploadType type)
        {
            var model = _sql.Select<Wenjian>().Where(f => f.id == id).ToOne() ?? new Wenjian() { wjlj = "/upload/touxiang/1.jpg" };
            ViewBag.ObjectId = objectId;
            ViewBag.UploadType = type;
            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> Avatar(long id, long objectId, UploadType type, IFormFile file)
        {
            var display = type.GetDisplayAttribute();
            var wenjian = new Wenjian() { id = id };
            if (file != null && file.Length > 0)
            {
                wenjian.ysmc = file.FileName;
                wenjian.wjlj = $"/upload/{display.Name}/{Path.GetRandomFileName().Replace(".", "dot")}{Path.GetExtension(file.FileName)}";

                if (wenjian.id > 0)
                {
                    await _sql.Update<Wenjian>().SetSource(wenjian).ExecuteAffrowsAsync();
                }
                else
                {
                    wenjian.id = await _sql.Insert<Wenjian>(wenjian).ExecuteIdentityAsync();
                }

                var filePath = Path.Combine(_hostEnvironment.WebRootPath, wenjian.wjlj.TrimStart('/'));
                if (!Directory.Exists(Path.GetDirectoryName(filePath)))
                    Directory.CreateDirectory(Path.GetDirectoryName(filePath));
                using var stream = System.IO.File.Create(filePath);
                await file.CopyToAsync(stream);

                await _sql.Ado.ExecuteNonQueryAsync($"update {display.GroupName} set {display.Name} = @wenjian where id = @id", new { wenjian = wenjian.id, id = objectId });
            }

            return RedirectToAction(nameof(Avatar), new { wenjian.id });
        }

        [HttpPost]
        public async Task<IActionResult> Editor(IFormFile file)
        {
            if (file != null && file.Length > 0)
            {
                var filePath = $"/upload/editor/{Path.GetRandomFileName().Replace(".", "dot")}{Path.GetExtension(file.FileName)}";
                var fullPath = Path.Combine(_hostEnvironment.WebRootPath, filePath.TrimStart('/'));
                if (!Directory.Exists(Path.GetDirectoryName(fullPath)))
                    Directory.CreateDirectory(Path.GetDirectoryName(fullPath));
                using var stream = System.IO.File.Create(fullPath);
                await file.CopyToAsync(stream);

                return Content(filePath);
            }

            return Content("没有上传文件");
        }
    }
}

CustomForm/Views/Home/Index.cshtml
@model HomeViewModel
@{
    ViewData["Menu"] = 0;
    ViewData["Title"] = "后台首页";
    var session = ViewContext.HttpContext.Session.Get<AdminSession>(nameof(AdminSession));
}

<main class="ftdms-layout-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <td>
                                            <h4><b>欢迎使用99HZ管理系统，若使用中有任何“系统”问题可联系：135 0916 3015</b></h4>
                                            <img src=~/qrcode.png width="180" />
                                            <br>
                                            手机扫码看效果
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            登录用户：@session.adminuser id：@session.adminid 权限：@session.adminqx
                                        </td>
                                    </tr>
                                </thead>
                            </table>
                        </div>

                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tbody>
                                    @if (Model.BBList.Any())
                                    {
                                        foreach (var item in Model.BBList)
                                        {
                                            <tr>
                                                <td>@(item.fbsj)</td>
                                                <td>@(item.username)</td>
                                                <td>【@(item.flmc)】</td>
                                                <td width="70%"><a href="@Url.Action("Show","BB", new { id = item.id })"> @*hynosql*@ @(item.fbbt)</a></td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                        <!-- 分页条码 -->
                        <pagination total-count="Model.BBListCount"></pagination>
                        <!--End 分页条码 -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

CustomForm/Views/Home/SetPass.cshtml
@model SetPassViewModel
@{
    ViewData["Menu"] = 9;
    ViewData["Title"] = "修改密码";
}

<main class="ftdms-layout-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        @using (Html.BeginForm(FormMethod.Post, true, new { @class = "site-form" }))
                        {
                            <div class="input-group m-b-10">
                                <span class="input-group-addon">原密码</span>
                                @Html.PasswordFor(m => m.pass0, new { @class="form-control", @required="required" })
                            </div>

                            <div class="input-group m-b-10">
                                <span class="input-group-addon">新密码</span>
                                @Html.PasswordFor(m => m.pass1, new { @class="form-control", @required="required" })
                            </div>

                            <div class="input-group m-b-10">
                                <span class="input-group-addon">新密码确认</span>
                                @Html.PasswordFor(m => m.pass2, new { @class="form-control", @required="required" })
                            </div>
                            <br>

                            <button type="submit" class="btn btn-primary">保存</button>
                            <button type="button" class="btn btn-default" onclick="javascript:history.go(-1);">返回</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

CustomForm/Views/Home/SetUser.cshtml
@model SetUserViewModel
@{
    ViewData["Menu"] = 9;
    ViewData["Title"] = "个人信息";
    var session = ViewContext.HttpContext.Session.Get<AdminSession>(nameof(AdminSession));
}

<main class="ftdms-layout-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">

                        <div class="edit-avatar-content">
                            <iframe frameborder="0" scrolling="no" height="320" width="500" name="upload" src="@Url.Action("Avatar","Upload",new { id = Model.touxiang, type = UploadType.Avatar, objectId = Model.id })"></iframe> <br>
                        </div>

                        @using (Html.BeginForm(FormMethod.Post, true, new { @class = "site-form" }))
                        {
                            @Html.HiddenFor(m => m.id)
                            <div class="input-group m-b-10">
                                <span class="input-group-addon">I D</span>
                                @Html.TextBoxFor(m => m.oaid, new { @class="form-control", @readonly="readonly" })
                            </div>

                            <div class="input-group m-b-10">
                                <span class="input-group-addon">姓名</span>
                                @Html.TextBoxFor(m => m.xingming, new { @class="form-control", @required="required" })
                            </div>

                            <div class="input-group m-b-10">
                                <span class="input-group-addon">所属单位</span>
                                @Html.TextBoxFor(m => m.danwei, new { @class="form-control", @required="required", @onkeyup="value=value.replace(/[^\u4E00-\u9FA5]/g,'')", @onbeforepaste="clipboardData.setData('text',clipboardData.getData('text').replace(/[^\u4E00-\u9FA5]/g,''))"  })
                            </div>

                            <div class="input-group m-b-10">
                                <span class="input-group-addon">所属上级</span>
                                @Html.DropDownListFor(m => m.pid,new List<SelectListItem>() { new SelectListItem(){ Selected = true, Text = session.adminuser ,Value = $"{session.adminid}" } },null, new { @class="form-control", @readonly="readonly"  })
                            </div>

                            <div class="input-group m-b-10">
                                <span class="input-group-addon">电话</span>
                                @Html.TextBoxFor(m => m.dianhua, new { @class="form-control", @required="required" })
                            </div>

                            <div class="input-group m-b-10">
                                <span class="input-group-addon">邮箱</span>
                                @Html.TextBoxFor(m => m.email, new { @type="email", @class="form-control", @aria_describedby="emailHelp"  })
                            </div>

                            <div class="input-group m-b-10">
                                <span class="input-group-addon">简介</span>
                                @Html.TextAreaFor(m => m.remark,new { @class="form-control", @rows="3" })
                            </div>

                            <button type="submit" class="btn btn-primary">保存</button>
                            <button type="button" class="btn btn-default" onclick="javascript:history.go(-1);">返回</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>